version: "3.3"
services:
    flask:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: queso:1
        working_dir: /opt/api/
        command: bash run.sh
        ports:
            - 5000:5000
        volumes:
            - ./api/:/opt/api/
        stdin_open: true
        tty: true
        env_file:
            - ./.env
        depends_on:
            - mongo
        expose:
            - 5000
        links:
            - mongo
    mongo:
        image: docker.io/mongo:latest
        ports:
            - 27017:27017
        env_file:
            - ./.env
        volumes:
            - ./data/DB:/data/dump/DB
    node:
        image: node:latest
        volumes:
            - ./frontend:/opt/frontend
        working_dir: /opt/frontend
        command: sh -c "npm install && npm run dev"
        ports: 
            - 3000:3000
    nginx:
        build:
            context: .
            dockerfile: ./Dockerfile.front
        ports:
            - 8080:80
    #     image: nginx:latest
    #     volumes:
    #         - ./frontend/build:/usr/share/nginx/html
        
